In [1]:
import pandas as pd

In [2]:
import statistics

In [5]:
import matplotlib.pyplot as plt

In [6]:
import numpy as np

# Classification

## Classification: Person, Object, and Place 
### baseline (RDF2vec<sub>oa</sub>, v100)

In [7]:
# it contains classification results by using university data
filename3 = "../experiment/kgrc_baseline_Person_Object_Place_wang2vec/classification_kgrc_person_object_place_results.csv"
data3 = pd.read_csv(filename3, keep_default_na=False)

In [8]:
data3.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
0,Classification,kgrc_person_object_place,1.0,NB,,0.600000
1,Classification,kgrc_person_object_place,1.0,NB,,0.600000
2,Classification,kgrc_person_object_place,1.0,NB,,0.614815
3,Classification,kgrc_person_object_place,1.0,NB,,0.605556
4,Classification,kgrc_person_object_place,1.0,NB,,0.609259

In [9]:
# the best method able to manage university data
best_result_baseline = data3[data3.accuracy==max(data3.accuracy)]

In [10]:
best_result_baseline

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
55,Classification,kgrc_person_object_place,1.0,SVM,C=10.0,0.8

### baseline (RDF2vec<sub>classic</sub>, v100)

In [11]:
filename3 = "../experiment/kgrc_baseline_Person_Object_Place_word2vec/classification_kgrc_person_object_place_results.csv"
data3 = pd.read_csv(filename3, keep_default_na=False)

In [12]:
best_result_baseline = data3[data3.accuracy==max(data3.accuracy)]

In [13]:
best_result_baseline

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
41,Classification,kgrc_person_object_place,1.0,SVM,C=10.0,0.744444

### RDF-star2Vec, v100

In [14]:
# it contains classification results by using university data
filename4 = "../experiment/kgrc_rdfstar2vec_5_5_Person_Object_Place_wang2vec/classification_kgrc_person_object_place_results.csv"
data4 = pd.read_csv(filename4, keep_default_na=False)

In [15]:
data4.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
0,Classification,kgrc_person_object_place,1.0,NB,,0.692593
1,Classification,kgrc_person_object_place,1.0,NB,,0.698148
2,Classification,kgrc_person_object_place,1.0,NB,,0.698148
3,Classification,kgrc_person_object_place,1.0,NB,,0.692593
4,Classification,kgrc_person_object_place,1.0,NB,,0.694444

In [16]:
best_result_rdfstar2vec = data4[data4.accuracy==max(data4.accuracy)]

In [17]:
best_result_rdfstar2vec

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
89,Classification,kgrc_person_object_place,1.0,SVM,C=1.0,0.822222

### RDF-star2Vec<sub>classic</sub>

In [18]:
filename4 = "../experiment/kgrc_rdfstar2vec_5_5_Person_Object_Place_word2vec/classification_kgrc_person_object_place_results.csv"
data4 = pd.read_csv(filename4, keep_default_na=False)

In [19]:
best_result_rdfstar2vec = data4[data4.accuracy==max(data4.accuracy)]

In [20]:
best_result_rdfstar2vec

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
61,Classification,kgrc_person_object_place,1.0,SVM,C=1.0,0.759259

## Classification: Situation, Statement, Thought
### baseline (RDF2vec<sub>oa</sub>, v100)

In [21]:
# it contains classification results by using university data
file_qt900_baseline = "../experiment/kgrc_baseline_Situation_Statement_Thought_wang2vec/classification_kgrc_qt900_results.csv"
data_qt900_baseline = pd.read_csv(file_qt900_baseline, keep_default_na=False)

In [22]:
data_qt900_baseline.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
0,Classification,kgrc_qt900,1.0,NB,,0.850000
1,Classification,kgrc_qt900,1.0,NB,,0.848889
2,Classification,kgrc_qt900,1.0,NB,,0.855556
3,Classification,kgrc_qt900,1.0,NB,,0.850000
4,Classification,kgrc_qt900,1.0,NB,,0.854444

In [23]:
# the best method able to manage university data
best_result_qt900_baseline = data_qt900_baseline[data_qt900_baseline.accuracy==max(data_qt900_baseline.accuracy)]

In [24]:
best_result_qt900_baseline

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
56,Classification,kgrc_qt900,1.0,SVM,C=100,0.976667
57,Classification,kgrc_qt900,1.0,SVM,C=1000,0.976667

### baseline (RDF2vec<sub>classic</sub>, v100)

In [25]:
file_qt900_baseline = "../experiment/kgrc_baseline_Situation_Statement_Thought_word2vec/classification_kgrc_qt900_results.csv"
data_qt900_baseline = pd.read_csv(file_qt900_baseline, keep_default_na=False)

In [26]:
best_result_qt900_baseline = data_qt900_baseline[data_qt900_baseline.accuracy==max(data_qt900_baseline.accuracy)]

In [27]:
best_result_qt900_baseline

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
49,Classification,kgrc_qt900,1.0,SVM,C=100,0.968889
50,Classification,kgrc_qt900,1.0,SVM,C=1000,0.968889

### RDF-star2Vec

In [28]:
file_qt900_rdfstar2vec = "../experiment/kgrc_rdfstar2vec_5_5_Situation_Statement_Thought_wang2vec/classification_kgrc_qt900_results.csv"
data_qt900_rdfstar2vec = pd.read_csv(file_qt900_rdfstar2vec, keep_default_na=False)

In [29]:
data_qt900_rdfstar2vec.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
0,Classification,kgrc_qt900,1.0,NB,,0.856667
1,Classification,kgrc_qt900,1.0,NB,,0.848889
2,Classification,kgrc_qt900,1.0,NB,,0.857778
3,Classification,kgrc_qt900,1.0,NB,,0.855556
4,Classification,kgrc_qt900,1.0,NB,,0.854444

In [30]:
best_result_qt900_rdfstar2vec = data_qt900_rdfstar2vec[data_qt900_rdfstar2vec.accuracy==max(data_qt900_rdfstar2vec.accuracy)]

In [31]:
best_result_qt900_rdfstar2vec

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
90,Classification,kgrc_qt900,1.0,SVM,C=10.0,0.974444
91,Classification,kgrc_qt900,1.0,SVM,C=100,0.974444
92,Classification,kgrc_qt900,1.0,SVM,C=1000,0.974444

### RDF-star2Vec<sub>classic</sub>, v100

In [32]:
file_qt900_rdfstar2vec = "../experiment/kgrc_rdfstar2vec_5_5_Situation_Statement_Thought_word2vec/classification_kgrc_qt900_results.csv"
data_qt900_rdfstar2vec = pd.read_csv(file_qt900_rdfstar2vec, keep_default_na=False)

In [33]:
best_result_qt900_rdfstar2vec = data_qt900_rdfstar2vec[data_qt900_rdfstar2vec.accuracy==max(data_qt900_rdfstar2vec.accuracy)]

In [34]:
best_result_qt900_rdfstar2vec

,task_name,gold_standard_file,coverage,model_name,model_configuration,accuracy
62,Classification,kgrc_qt900,1.0,SVM,C=10.0,0.971111
63,Classification,kgrc_qt900,1.0,SVM,C=100,0.971111
64,Classification,kgrc_qt900,1.0,SVM,C=1000,0.971111

# Clustering
## Clustering: Person, Object, and Place
### baseline (RDF2vec<sub>oa</sub>, v100)

In [35]:
# it contains classification results by using university data
filename = "../experiment/kgrc_baseline/clustering_kgrc_person_object_place_results.csv"

In [36]:
data = pd.read_csv(filename, keep_default_na=False)

In [37]:
data.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_person_object_place,1.0,DBSCAN,metric=cosine,63,0.009367,0.029786,0.140961,0.145759,0.143320,0.143320,0.359259
1,Clustering,kgrc_person_object_place,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.388012,0.369237,0.364213,0.378912,0.371417,0.371417,0.751852
2,Clustering,kgrc_person_object_place,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.063939,0.063192,0.065374,0.067496,0.066418,0.066418,0.418519
3,Clustering,kgrc_person_object_place,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.029551,0.029486,0.030925,0.035386,0.033006,0.033006,0.429630

### baseline (RDF2vec<sub>classic</sub>, v100)

In [38]:
# it contains classification results by using university data
filename = "../experiment/kgrc_baseline_word2vec/clustering_kgrc_person_object_place_results.csv"

In [39]:
data = pd.read_csv(filename, keep_default_na=False)

In [40]:
data.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_person_object_place,1.0,DBSCAN,metric=cosine,34,0.001481,0.002975,0.063277,0.105896,0.079218,0.079218,0.335185
1,Clustering,kgrc_person_object_place,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.188507,0.178834,0.169228,0.196465,0.181832,0.181832,0.557407
2,Clustering,kgrc_person_object_place,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,-0.002196,-0.001946,0.001471,0.001502,0.001486,0.001486,0.346296
3,Clustering,kgrc_person_object_place,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.018149,0.038748,0.035437,0.053689,0.042694,0.042694,0.407407

### RDF-star2Vec, v100

In [41]:
# it contains classification results by using university data
filename2 = "../experiment/kgrc_rdfstar2vec/clustering_kgrc_person_object_place_results.csv"
data2 = pd.read_csv(filename2, keep_default_na=False)

In [42]:
data2.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_person_object_place,1.0,DBSCAN,metric=cosine,254,0.034208,0.063649,0.597618,0.151699,0.241975,0.241975,0.179630
1,Clustering,kgrc_person_object_place,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.653051,0.583721,0.584231,0.586039,0.585134,0.585134,0.870370
2,Clustering,kgrc_person_object_place,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.065474,0.064144,0.064799,0.070326,0.067449,0.067449,0.437037
3,Clustering,kgrc_person_object_place,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.049630,0.069604,0.066461,0.081166,0.073081,0.073081,0.446296

### RDF-star2Vec<sub>classic</sub>, v100

In [44]:
# it contains classification results by using university data
filename2 = "../experiment/kgrc_rdfstar2vec_word2vec/clustering_kgrc_person_object_place_results.csv"
data2 = pd.read_csv(filename2, keep_default_na=False)

In [45]:
data2.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_person_object_place,1.0,DBSCAN,metric=cosine,165,0.002414,0.028129,0.348719,0.126634,0.185797,0.185797,0.211111
1,Clustering,kgrc_person_object_place,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.102966,0.091715,0.091396,0.098716,0.094915,0.094915,0.477778
2,Clustering,kgrc_person_object_place,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.074483,0.065749,0.066465,0.071827,0.069042,0.069042,0.457407
3,Clustering,kgrc_person_object_place,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.012009,0.040869,0.038029,0.054230,0.044707,0.044707,0.387037

<hr>

## Clustering: Situation, Statement, and Thought
### baseline (RDF2vec<sub>oa</sub>, v100)

In [46]:
file_qt900_baseline = "../experiment/kgrc_baseline/clustering_kgrc_qt900_results.csv"

In [47]:
data_qt900_baseline = pd.read_csv(file_qt900_baseline, keep_default_na=False)

In [48]:
data_qt900_baseline.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_qt900,1.0,DBSCAN,metric=cosine,57,0.051120,0.110046,0.205686,0.118748,0.150569,0.150569,0.354444
1,Clustering,kgrc_qt900,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.314086,0.323817,0.322547,0.327898,0.325201,0.325201,0.690000
2,Clustering,kgrc_qt900,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.177368,0.187633,0.179125,0.200875,0.189378,0.189378,0.564444
3,Clustering,kgrc_qt900,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.366361,0.341999,0.339606,0.347176,0.343349,0.343349,0.690000

### baseline (RDF2vec<sub>classic</sub>, v100)

In [53]:
file_qt900_baseline = "../experiment/kgrc_baseline_word2vec/clustering_kgrc_qt900_results.csv"

In [54]:
data_qt900_baseline = pd.read_csv(file_qt900_baseline, keep_default_na=False)

In [55]:
data_qt900_baseline.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_qt900,1.0,DBSCAN,metric=cosine,23,0.013422,0.058516,0.069357,0.118824,0.087589,0.087589,0.385556
1,Clustering,kgrc_qt900,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.440896,0.453186,0.429561,0.482200,0.454361,0.454361,0.708889
2,Clustering,kgrc_qt900,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.358706,0.353839,0.345784,0.365113,0.355186,0.355186,0.672222
3,Clustering,kgrc_qt900,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.335883,0.322633,0.305836,0.344665,0.324092,0.324092,0.668889

### RDF-star2Vec, v100

In [56]:
file_qt900_rdfstar2vec = "../experiment/kgrc_rdfstar2vec/clustering_kgrc_qt900_results.csv"

In [57]:
data_qt900_rdfstar2vec = pd.read_csv(file_qt900_rdfstar2vec, keep_default_na=False)

In [58]:
data_qt900_rdfstar2vec.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_qt900,1.0,DBSCAN,metric=cosine,68,0.071913,0.109320,0.242777,0.108980,0.150432,0.150432,0.287778
1,Clustering,kgrc_qt900,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.066160,0.069586,0.066342,0.077824,0.071626,0.071626,0.435556
2,Clustering,kgrc_qt900,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.064886,0.096964,0.091475,0.107751,0.098948,0.098948,0.491111
3,Clustering,kgrc_qt900,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.065901,0.099402,0.093665,0.110485,0.101382,0.101382,0.492222

### RDF-star2Vec<sub>classic</sub>, v100

In [59]:
file_qt900_rdfstar2vec = "../experiment/kgrc_rdfstar2vec_word2vec/clustering_kgrc_qt900_results.csv"

In [60]:
data_qt900_rdfstar2vec = pd.read_csv(file_qt900_rdfstar2vec, keep_default_na=False)

In [61]:
data_qt900_rdfstar2vec.head()

,task_name,gold_standard_file,coverage,model_name,model_configuration,num_clusters,adjusted_rand_index,adjusted_mutual_info_score,homogeneity_score,completeness_score,v_measure_score,normalized_mutual_info_score,clustering_accuracy
0,Clustering,kgrc_qt900,1.0,DBSCAN,metric=cosine,35,0.076057,0.107865,0.190902,0.099204,0.130561,0.130561,0.291111
1,Clustering,kgrc_qt900,1.0,KMeans,"metric=enclidean, n_clusters=3",3,0.066160,0.069586,0.066342,0.077824,0.071626,0.071626,0.435556
2,Clustering,kgrc_qt900,1.0,Agglomerative clustering,"metric=cosine, n_clusters=3",3,0.066160,0.069586,0.066342,0.077824,0.071626,0.071626,0.435556
3,Clustering,kgrc_qt900,1.0,Ward hierarchical clustering,"metric=cosine, n_clusters=3",3,0.066160,0.069586,0.066342,0.077824,0.071626,0.071626,0.435556

<hr>

# Entity Relatedness

## baseline (RDF2vec<sub>oa</sub>, v100)

In [62]:
# it contains classification results by using university data
filename_er_baseline = "../experiment/kgrc_baseline/entityRelatedness_kgrc_entity_relatedness_results.csv"
data_er_baseline = pd.read_csv(filename_er_baseline, keep_default_na=False)

In [63]:
data_er_baseline

,task_name,gold_standard_file,coverage,entity_name,kendalltau_correlation,kendalltau_pvalue
0,EntityRelatedness,kgrc_entity_relatedness,1.0,ci:Windibank,-0.288889,0.291248
1,EntityRelatedness,kgrc_entity_relatedness,1.0,sb:Julia,0.155556,0.600654
2,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Roundhay,-0.244444,0.380720
3,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Henry,0.066667,0.861801
4,EntityRelatedness,kgrc_entity_relatedness,1.0,sl:Fitzroy_Simpson,0.200000,0.484313
5,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Lady_Brackenstall,0.111111,0.727490
6,EntityRelatedness,kgrc_entity_relatedness,1.0,sl:John_Straker,0.377778,0.155742
7,EntityRelatedness,kgrc_entity_relatedness,1.0,sl:Silver_Blaze,-0.200000,0.484313
8,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Jack_Croker,-0.422222,0.108313
9,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Sir_Eustace_Brackenstall,0.155556,0.600654
10,EntityRelatedness,kgrc_entity_relatedness,1.0,sb:Roylott,0.333333,0.216373
11,EntityRelatedness,kgrc_entity_relatedness,1.0,dm:Cubitt,-0.022222,1.000000
12,EntityRelatedness,kgrc_entity_relatedness,1.0,ci:Sutherland,-0.111111,0.727490
13,EntityRelatedness,kgrc_entity_relatedness,1.0,rp:Blessington,0.066667,0.861801
14,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Nancy,0.200000,0.484313
15,EntityRelatedness,kgrc_entity_relatedness,1.0,dm:Abe_Slaney,0.155556,0.600654
16,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Barclay,-0.022222,1.000000
17,EntityRelatedness,kgrc_entity_relatedness,1.0,rp:Percy_Trevelyan,-0.377778,0.155742
18,EntityRelatedness,kgrc_entity_relatedness,1.0,sb:Helen,-0.155556,0.600654
19,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Holmes,-0.022222,1.000000
20,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Mortimer,0.466667,0.072550

In [64]:
max_er_result_baseline = data_er_baseline[data_er_baseline.kendalltau_correlation == max(data_er_baseline.kendalltau_correlation)]

In [65]:
max_er_result_baseline

,task_name,gold_standard_file,coverage,entity_name,kendalltau_correlation,kendalltau_pvalue
20,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Mortimer,0.466667,0.07255

## baseline (RDF2vec<sub>classic</sub>, v100)

In [66]:
filename_er_baseline = "../experiment/kgrc_baseline_word2vec/entityRelatedness_kgrc_entity_relatedness_results.csv"
data_er_baseline = pd.read_csv(filename_er_baseline, keep_default_na=False)

In [67]:
max_er_result_baseline = data_er_baseline[data_er_baseline.kendalltau_correlation == max(data_er_baseline.kendalltau_correlation)]

In [68]:
max_er_result_baseline

,task_name,gold_standard_file,coverage,entity_name,kendalltau_correlation,kendalltau_pvalue
12,EntityRelatedness,kgrc_entity_relatedness,1.0,ci:Sutherland,0.422222,0.108313
14,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Nancy,0.422222,0.108313

## RDF-star2Vec, v100

In [69]:
# it contains classification results by using university data
filename_er_rdfstar2vec = "../experiment/kgrc_rdfstar2vec/entityRelatedness_kgrc_entity_relatedness_results.csv"
data_er_rdfstar2vec = pd.read_csv(filename_er_rdfstar2vec, keep_default_na=False)

In [70]:
data_er_rdfstar2vec

,task_name,gold_standard_file,coverage,entity_name,kendalltau_correlation,kendalltau_pvalue
0,EntityRelatedness,kgrc_entity_relatedness,1.0,ci:Windibank,0.200000,0.484313
1,EntityRelatedness,kgrc_entity_relatedness,1.0,sb:Julia,-0.155556,0.600654
2,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Roundhay,-0.244444,0.380720
3,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Henry,0.111111,0.727490
4,EntityRelatedness,kgrc_entity_relatedness,1.0,sl:Fitzroy_Simpson,0.155556,0.600654
5,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Lady_Brackenstall,0.511111,0.046623
6,EntityRelatedness,kgrc_entity_relatedness,1.0,sl:John_Straker,0.333333,0.216373
7,EntityRelatedness,kgrc_entity_relatedness,1.0,sl:Silver_Blaze,-0.111111,0.727490
8,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Jack_Croker,0.555556,0.028609
9,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Sir_Eustace_Brackenstall,0.377778,0.155742
10,EntityRelatedness,kgrc_entity_relatedness,1.0,sb:Roylott,0.066667,0.861801
11,EntityRelatedness,kgrc_entity_relatedness,1.0,dm:Cubitt,0.111111,0.727490
12,EntityRelatedness,kgrc_entity_relatedness,1.0,ci:Sutherland,0.377778,0.155742
13,EntityRelatedness,kgrc_entity_relatedness,1.0,rp:Blessington,0.155556,0.600654
14,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Nancy,0.422222,0.108313
15,EntityRelatedness,kgrc_entity_relatedness,1.0,dm:Abe_Slaney,-0.111111,0.727490
16,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Barclay,0.066667,0.861801
17,EntityRelatedness,kgrc_entity_relatedness,1.0,rp:Percy_Trevelyan,-0.066667,0.861801
18,EntityRelatedness,kgrc_entity_relatedness,1.0,sb:Helen,0.244444,0.380720
19,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Holmes,0.466667,0.072550
20,EntityRelatedness,kgrc_entity_relatedness,1.0,df:Mortimer,0.200000,0.484313

In [71]:
max_er_result_rdfstar2vec = data_er_rdfstar2vec[data_er_rdfstar2vec.kendalltau_correlation == max(data_er_rdfstar2vec.kendalltau_correlation)]

In [72]:
max_er_result_rdfstar2vec

,task_name,gold_standard_file,coverage,entity_name,kendalltau_correlation,kendalltau_pvalue
8,EntityRelatedness,kgrc_entity_relatedness,1.0,ag:Jack_Croker,0.555556,0.028609

## RDF-star2Vec<sub>classic</sub>, v100

In [73]:
filename_er_rdfstar2vec = "../experiment/kgrc_rdfstar2vec_word2vec/entityRelatedness_kgrc_entity_relatedness_results.csv"
data_er_rdfstar2vec = pd.read_csv(filename_er_rdfstar2vec, keep_default_na=False)

In [74]:
max_er_result_rdfstar2vec = data_er_rdfstar2vec[data_er_rdfstar2vec.kendalltau_correlation == max(data_er_rdfstar2vec.kendalltau_correlation)]

In [75]:
max_er_result_rdfstar2vec

,task_name,gold_standard_file,coverage,entity_name,kendalltau_correlation,kendalltau_pvalue
14,EntityRelatedness,kgrc_entity_relatedness,1.0,cm:Nancy,0.6,0.016666

# Document Similarity (Quoted Triple Similarity)
## baseline (RDF2vec<sub>oa</sub>, v100)

In [76]:
filename_ds_baseline = "../experiment/kgrc_baseline/documentSimilarity_LP50_results.csv"
data_ds_baseline = pd.read_csv(filename_ds_baseline, keep_default_na=False)

In [77]:
data_ds_baseline

,task_name,gold_standard_file,coverage,conf,pearson_score,spearman_score,harmonic_mean
0,DocumentSimilarity,LP50,1.0,with_weights,0.02995,0.003189,0.005764
1,DocumentSimilarity,LP50,1.0,without_weights,0.02995,0.003189,0.005764

## baseline (RDF2vec<sub>classic</sub>, v100)

In [78]:
filename_ds_baseline = "../experiment/kgrc_baseline_word2vec/documentSimilarity_LP50_results.csv"
data_ds_baseline = pd.read_csv(filename_ds_baseline, keep_default_na=False)

In [79]:
data_ds_baseline

,task_name,gold_standard_file,coverage,conf,pearson_score,spearman_score,harmonic_mean
0,DocumentSimilarity,LP50,1.0,with_weights,0.032529,0.010109,0.015424
1,DocumentSimilarity,LP50,1.0,without_weights,0.032529,0.010109,0.015424

## RDF-star2Vec, v100

In [80]:
filename_ds_rdfstar2vec = "../experiment/kgrc_rdfstar2vec/documentSimilarity_LP50_results.csv"
data_ds_rdfstar2vec = pd.read_csv(filename_ds_rdfstar2vec, keep_default_na=False)

In [81]:
data_ds_rdfstar2vec

,task_name,gold_standard_file,coverage,conf,pearson_score,spearman_score,harmonic_mean
0,DocumentSimilarity,LP50,1.0,with_weights,0.100002,0.039053,0.05617
1,DocumentSimilarity,LP50,1.0,without_weights,0.100002,0.039053,0.05617

## RDF-star2Vec<sub>classic</sub>, v100

In [82]:
filename_ds_rdfstar2vec = "../experiment/kgrc_rdfstar2vec_word2vec/documentSimilarity_LP50_results.csv"
data_ds_rdfstar2vec = pd.read_csv(filename_ds_rdfstar2vec, keep_default_na=False)

In [83]:
data_ds_rdfstar2vec

,task_name,gold_standard_file,coverage,conf,pearson_score,spearman_score,harmonic_mean
0,DocumentSimilarity,LP50,1.0,with_weights,0.116514,0.056846,0.076412
1,DocumentSimilarity,LP50,1.0,without_weights,0.116514,0.056846,0.076412

<hr>